[package]
name = "merge2dirsc1310"
version = "0.1.0"
authors = ["jp <jpercyasnet@yahoo.com>"]
edition = "2021"
publish = false

[dependencies]
iced = "^0"
rfd = "^0"
chrono = "^0"
kamadak-exif = "^0"
regex = "^0"
